### ISSUE TITLE
Analysis fails on empty main

### ISSUE THREAD

**Issue by aubertc** [seiller/pymwp#4]
The following C code:

```C
int main(){
}
```

causes the analysis to return

```python
Traceback (most recent call last):
  File "pymwp/Analysis.py", line 353, in <module>
    rels, combinations = analysis()
  File "pymwp/Analysis.py", line 309, in analysis
    return compute_relation(name)
  File "pymwp/Analysis.py", line 322, in compute_relation
    for stmt in function_body.block_items:
TypeError: 'NoneType' object is not iterable
```

The expected behavior should probably be an empty matrix?

**Comment by aubertc** [comment]
A slightly different error message is returned on empty files.

```python
Traceback (most recent call last):
  File "pymwp/Analysis.py", line 353, in <module>
    rels, combinations = analysis()
  File "pymwp/Analysis.py", line 309, in analysis
    return compute_relation(name)
  File "pymwp/Analysis.py", line 319, in compute_relation
    function_body = ast.ext[0].body
IndexError: list index out of range
```

**Comment by nkrusch** [comment]
I have a fix for this in analysis branch, but it is not ready to merge yet.
